### ISSUE TITLE
转换遗漏?

### ISSUE THREAD

**Issue by K1GP** [zfl9/gfwlist2privoxy#1]
有些开头和结尾的.*以及其中一部分%2F是遗漏了没有被转换?

**Comment by zfl9** [comment]
`%2F` 是字符 `/` 的 URL 编码，转换遗漏的话可能是有的。不过日常使用绝对没问题。

**Comment by K1GP** [comment]
知道是/,所以我说的是一部分%2F.......

**Comment by zfl9** [comment]
我使用过程中暂未发现所谓的 %2F。还麻烦您提出改进意见（最好是代码）

2018-02-06 17:44 GMT+08:00 K1GP <notifications@github.com>:

**Comment by K1GP** [comment]
https://github.com/zfl9/gfwlist2privoxy/blob/master/gfwlist.action内搜.*和%2F
比如：
.*.wordpress.com和.wordpress.com
.google.*和.google.
.bbc.com和.bbc.com%2Fzhongwen
.bbs.sina.com和.bbs.sina.com%2F
只是多余重复了当然不会有问题

**Comment by zfl9** [comment]
随便了，原版 gfwlist.txt 就有这些。

**Comment by K1GP** [comment]
随便
