### ISSUE TITLE
脚本 bug "echo -e"

### ISSUE THREAD

**Issue by bao3** [zfl9/gfwlist2privoxy#4]
在脚步中有 一下语句：
`
echo -e "# Generated by gfwlist2privoxy at $(date '+%F %T')\n{+forward-override{forward-socks5 $1 .}}" >${gfwlist_action}
`
这个本身是 OK 的，但是在 `Linux dns 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux` ，执行 `sh gfwlist2privoxy MYPROXY:PORT`  后，会出错：

` Fatal error: can't load actions file '/etc/privoxy/gfwlist.action': line 1 should begin with a '{': -e`

经过检查，是在  `gfwlist.action`第一行，多出了 `-e` 。
所以请修复一下，我就不提 PR 了。

PS：感谢你的项目，很好用。

**Comment by zfl9** [comment]
你将脚本的 `#!/bin/sh` 改为 `#!/bin/bash` 再次运行会有此问题吗？哦不，你使用 `/bin/bash gfwlist2privoxy PROXY:PORT` 会不会有此问题？
