### ISSUE TITLE
生成的gfwlist.action无法使用

### ISSUE THREAD

**Issue by julianhu1979** [zfl9/gfwlist2privoxy#7]
生成的在gfwlist.action 文件在没有以下配置的情况下，无法使用 
{ +forward-override{forward .}} /

**Comment by zfl9** [comment]
???我需要更详细的信息

**Comment by julianhu1979** [comment]
能否加上上面的配置在生成的文件中

**Comment by zfl9** [comment]
你自己先加上去吧。我有空再研究这条配置的意思（我其实是希望你能解释他的作用。。。）
